### ISSUE TITLE
Cut/Paste between cells does not work - Cut deletes the whole table

### ISSUE THREAD

**Issue by markusvoelter** [slisson/mps-tables#88]

**Comment by slisson** [comment]
CUT works for me. Only the selected cell is deleted. Here is an example for a PASTE handler (set it on the parent collection of the table):

![screen shot 2015-05-05 at 11 23 32](https://cloud.githubusercontent.com/assets/1543361/7469954/39c9ecb8-f319-11e4-83d2-3bb147dacf37.png)
