### ISSUE TITLE
New nodes are not initialized when adding though table {...} editor

### ISSUE THREAD

**Issue by vlsi** [slisson/mps-tables#95]
Concept `HttpArgument` has `elementName : StringProperty[1]` children link. When adding such entity via table editor (like in https://github.com/slisson/mps-tables/issues/91) `elementName` field is not initialized.
In other words, for newly created entity the row is empty.

When using default RefNodeList vertical editor, newly created `HttpArgument` nodes have elementName initialized with a `StringProperty`.

I suspect nodes are created via `new`, while they should be created via `new initialized` (see https://youtrack.jetbrains.com/issue/MPS-11788)

MPS 3.2.2

**Comment by slisson** [comment]
"new initialized node" is used in "vertical%...%". It is working in my examples. There must be some other reason.

**Comment by vlsi** [comment]
Here's the case: rows are initialized properly when left/right insertion placeholders are used.
However, if cursor is in the middle of the table and you hit enter, then new non-initialized row is created.

As far as I can understand, ChildNodesInsertAction is probably not using "new initialized". Not sure what "SConceptOperations.createNewNode" stands for.

**Comment by vlsi** [comment]
I hit "preview generated text" on my editor and it looks like "new initialized node" is generated into `SNodeFactoryOperations.createNewNode`:

```
gridElement.setRightRowCreateHandler(new IRowCreateHandler() {
          public void create() {
            ListSequence.fromList(SLinkOperations.getChildren(node,
MetaAdapterFactory.getContainmentLink(0xa2d5158a651d4987L, 0xabdd795f7a40c8c2L, 0x6209131a2befe683L, 0x6209131a2befeb04L, "arguments")))
.insertElement(yFinal + 1,
  SNodeFactoryOperations.createNewNode(
    SNodeFactoryOperations.asInstanceConcept(
      MetaAdapterFactory.getConcept(0xa2d5158a651d4987L, 0xabdd795f7a40c8c2L, 0x6209131a2befec20L, "com.github.vlsi.jmeter.structure.HttpArgument")), null));
          }
        });
```

**Comment by vlsi** [comment]
Can you please clarify what is the way to build mps-tables?

Is there a "super-project" somewhere?
Should I download git repos one-by-one and add open them at once in a clean MPS?

If I install mbeddr plugins, then MPS somehow ignores mps-tables' project files.
If I use clean MPS, and open mps-tables code, then all the code is red, lots of compilation errors (e.g. "can't find model: de.itemis.mps.selection.runtime.mouse" when compiling mps-tables.runtime), etc.

**Comment by slisson** [comment]
There is a parent project at https://github.com/slisson/mps-all/ for all my MPS projects, that contains one build script for all of them. You can build it with these commands:
```
git clone --recursive https://github.com/slisson/mps-all.git
cd mps-all
ant -Dmps.home="/path/to/mps3.2.1"
```
