### ISSUE TITLE
Table Editor does not show "headers" children

### ISSUE THREAD

**Issue by RobertWalter83** [slisson/mps-tables#99]
Hi,

I try to figure out how I can make the table editor allow me to specify headers.
In the state machine example, I can see how it is supposed to look like:

![mps1](https://cloud.githubusercontent.com/assets/5462981/11445945/42f3caf6-9531-11e5-9f1d-dafd55b5f99a.png)

But I do not understant how to get them to show up when I create my own table.
I can see the "cell alternation" in the table editor itself,, but I do not understand what that means and I cannot find any documentation about it.

All I get it is this:
![mps2](https://cloud.githubusercontent.com/assets/5462981/11445969/8953dd06-9531-11e5-838e-289a4fd273c8.png)

**Comment by slisson** [comment]
At this position the headers are deprecated. Start with a for example a "vertical" and insert your headers in the "c<>" part.

**Comment by RobertWalter83** [comment]
I see, thanks.

**Comment by ftomassetti** [comment]
This helps. However it is not clear to me how I could add the single cells: I have a vertical and an horizontal annidated in the c<> part of the vertical. It is not clear where I should define the single cells.

**Comment by slisson** [comment]
I assume your concept contains a list of nodes that represent the rows of your table. Then you use a "vertical%...%". Use a "partial table" in the editor of your row concept to define the cells.
